version: "3.3"

services:
  traefik:
    container_name: "traefik"
    hostname: "traefik"
    image: "traefik:v2.6"
    command:
      - "--configfile=/srv/traefik/traefik.yml"
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      # - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/srv/traefik/:/srv/traefik/"
    environment:
      DO_AUTH_TOKEN: "${DO_AUTH_TOKEN}"

  web-app:
    container_name: "web-app"
    hostname: "web-app"
    image: ghcr.io/kindelia/kindelia.org:staging

  kindelia-node-test:
    image: "kelvinss/kindelia-node"
    ports:
      - "42000:42000/udp"
