---

- hosts: all
  tasks:
    # - name: "Copy block code"
    #   copy:
    #     src:  'block.kdl'
    #     dest: '/srv/kindelia-node/block.kdl'

    - name: "(Re)start service"
      systemd:
        # scope: user
        service: 'kindelia-node'
        state: restarted
