---

- hosts: all

  vars:
    # repo: 'Kindelia/Kindelia'
    # version: 'master'
    repo: 'quleuber/Kindelia'
    version: 'testnet'

  tasks:
    - name: "Checkout node code"
      ansible.builtin.git:
        accept_newhostkey: true
        repo: 'https://github.com/{{repo}}.git'
        dest: /srv/kindelia-node/repo
        version: '{{version}}'

    - name: "Build node"
      shell:
        chdir: '/srv/kindelia-node/repo'
        cmd: '/root/.cargo/bin/cargo build --release'
      register: cargo_build
      changed_when: "'Compiling' in cargo_build.stderr"

    # - name: "Install node"
    #   shell:
    #     chdir: '/srv/kindelia-node/repo'
    #     cmd: '/root/.cargo/bin/cargo install --path .'

    - name: "Stop service"
      ignore_errors: true
      systemd:
        service: 'kindelia-node'
        state: stopped

    - name: "Copy node binary"
      ansible.builtin.copy:
        remote_src: true
        mode: preserve
        src: '/srv/kindelia-node/repo/target/release/kindelia'
        dest: '/usr/local/bin/kindelia'
