---

- hosts: all
  tasks:

    - name: "Copy block code"
      copy:
        src:  'block.kdl'
        dest: '/srv/kindelia-node/block.kdl'

    - name: "Deploy service definition"
      copy:
        src:  'kindelia-node.service'
        dest: '/etc/systemd/system/kindelia-node.service'

    # - name: "Start service"
    #   systemd:
    #     scope: user
    #     service: 'kindelia-node'
    #     state: started

    - name: "(Re)start service"
      systemd:
        # scope: user
        service: 'kindelia-node'
        state: restarted
