---

- hosts: all
  tasks:

    - name: "Deploy journald.conf"
      template:
        src:  'journald.conf.j2'
        dest: '/etc/systemd/journald.conf'

    - name: "Restart journald"
      systemd:
        service: 'systemd-journald'
        state: restarted
